### ISSUE TITLE
As obs Browsersource?

### ISSUE THREAD

**Issue by Dschogo** [Jaapp-/miband-5-heart-rate-monitor#1]
Hey, first of all awesome tool :D

Is it possible to auto connect to a specific band per url? (like https://miband-5-heart-rate-monitor.netlify.app/?MIBANDKEY)
That would be very useful to include this feature as a browsersource directly in obs (if that has bluetooth support)

**Comment by Dschogo** [comment]
Okey i managed to flag the key input field as password in the browser, so it automatically fills in the key.

**Comment by Rheinhauss** [comment]
Would you kindly tell me how do you manage to use this repo as obs Browsersource?
I tried to trigger connectButton.click() method but it told me `Failed to execute 'requestDevice' on 'Bluetooth': Must be handling a user gesture to show a permission request.`
Many thanks.

**Comment by Dschogo** [comment]
Ehm kind of forgot. But what works for me (did it last week). 
I entered the key and made then an "app" out of the window (menu -> create shortcut -> open as new window). Connect once. After that everytime i open the "app" the key is already filled in.
I dont know if thats all you have to do or if there was still some configuration left from my previous setup.
